### ISSUE TITLE
Kernel build failed for zynq-zed-adv7511 on petalinux 2021.1 and meta-adi staging/2021_1-support.

### ISSUE THREAD

**Issue by oQuQu** [analogdevicesinc/meta-adi#105]
**Environment (please complete the following information):**
 - Project to build: zynq-zed-adv7511
 - Petalinux version: 2021.1
 - HDL branch: master
 - META-ADI branch: staging/2021_1-support
 - Using meta-adi petalinux docker image? No

**Describe the bug**
Kernel build failed for zynq-zed-adv7511 on petalinux 2021.1 and meta-adi staging/2021_1-support. 
( can not find <zynq-zed.dtsi> )

**Screenshots**
![image](https://user-images.githubusercontent.com/13028482/141424688-de93179c-7544-4dbf-b440-40d5ca30f682.png)
![image](https://user-images.githubusercontent.com/13028482/141424837-19b72fc6-042f-4b59-849d-8ab638a38c66.png)

**Comment by nunojsa** [comment]
That is odd. I recently ran a successful build on this project. Just started a new one now to see if something changed... Moreover, your error looks very weird (that file should exist). Did you already tried a clean build?

**Comment by nunojsa** [comment]
Well, the build went just fine for me... So I would really suggest for you to make a clean build of the project.

**Comment by nunojsa** [comment]
Any updates here? I will wait a few days more and close this issue if nothing new comes...

**Comment by chegbeli** [comment]
This issue might appear if /bin/sh is not set to bash. 
In order to change set it properly please try this:
` sudo ln -sf bash /bin/sh`
