### ISSUE TITLE
 Package Version (5.10-adi_master+gitAUTOINC+machine) does not match of kernel being built (5.15)

### ISSUE THREAD

**Issue by JIH82** [analogdevicesinc/meta-adi#119]
**Environment (please complete the following information):**
 - Project to build: meta-adi
 - Petalinux version: 2021.2
 - HDL branch: master
 - META-ADI branch: master
 - Using meta-adi petalinux docker image?
 -   no?

**Describe the bug**
I built this config february 15th 2023 and it worked fine. now it seems the kernal version has been updated from 5.10 to 5.15 but the recipe has not been updated to match this change
**Screenshots**
ERROR: linux-xlnx-5.10-adi_master+gitAUTOINC+machine-r0 do_kernel_version_sanity_check: Package Version (5.10-adi_master+gitAUTOINC+machine) does not match of kernel being built (5.15). Please update the PV variable to match the kernel source or set KERNEL_VERSION_SANITY_SKIP="1" in your recipe.
ERROR: linux-xlnx-5.10-adi_master+gitAUTOINC+machine-r0 do_kernel_version_sanity_check: Execution of '/home/j/peta_projects/adi/zcu102-A/build/tmp/work/zynqmp_generic-xilinx-linux/linux-xlnx/5.10-adi_master+gitAUTOINC+machine-r0/temp/run.do_kernel_version_sanity_check.49351' failed with exit code 1:
WARNING: exit code 1 from a shell command.

ERROR: Logfile of failure stored in: /home/j/peta_projects/adi/zcu102-A/build/tmp/work/zynqmp_generic-xilinx-linux/linux-xlnx/5.10-adi_master+gitAUTOINC+machine-r0/temp/log.do_kernel_version_sanity_check.49351
ERROR: Task (/home/j/peta_projects/adi/zcu102-A/components/yocto/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx_2021.2.bb:do_kernel_version_sanity_check) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5301 tasks of which 4234 didn't need to be rerun and 1 failed.

**Additional context**

**Comment by nunojsa** [comment]
yeah, this is expected and I'm working on fixing this... We need to update to petalinux 2022.2 in the master branch. If you want to continue 2021.2, use the 2021_R2 branch.

BTW, sorry for the late reply
