### ISSUE TITLE
Warnings about compatibility

### ISSUE THREAD

**Issue by ckoehler** [analogdevicesinc/meta-adi#13]
When I include your layer in Yocto, I get these warnings:

> WARNING:
>  Layer meta-adi-xilinx should set LAYERSERIES_COMPAT_meta-adi-xilinx in its conf/layer.conf file to list the core layer names it is compatible with.                                                                                  
> WARNING: Layer meta-adi-core should set LAYERSERIES_COMPAT_meta-adi-core in its conf/layer.conf file to list the core layer names it is compatible with.

**Comment by nunojsa** [comment]
These layers for now were only tested with petalinux. Still, these variables should be set as `LAYERDEPENDS`. This will be fixed...
