### ISSUE TITLE
Several recipies point to invalid analogdevicesinc branches

### ISSUE THREAD

**Issue by mbush00** [analogdevicesinc/meta-adi#133]
The following recipes point to the 'master' branch which seems to have been replaced with a 'main' branch:

- meta-adi-core/recipes-core/fru-tools/fru-tools_0.8.1.5.bb
- meta-adi-core/recipes-core/jesd-status/jesd-status_dev.bb
- meta-adi-xilinx/recipes-support/adrv9009-zu11eg-fan-control-daemon/adrv9009-zu11eg-fan-control_dev.bb

I've replaced the branch names in my local repo and it seems to work. But I'm not sure if this is the new way going forward, or someone else made a mistake by removing the master branches.

**Comment by nunojsa** [comment]
yeah, should be fixed by #132
