### ISSUE TITLE
Device-Tree isuue

### ISSUE THREAD

**Issue by pollai2** [analogdevicesinc/meta-adi#137]
**Environment (please complete the following information):**
 - Project to build: zc706 with AD9371
 - Petalinux version:2021.2
 - HDL branch:https://github.com/analogdevicesinc/hdl/tree/hdl_2021_r2
 - META-ADI branch:https://github.com/analogdevicesinc/meta-adi/tree/2021_R2
 - Using meta-adi petalinux docker image?

**Describe the bug**
I am Creating BSP project in petalinux and successfully build BSP project, then download the met-adi layers from github and placed outside of the project,run this command 
"echo "KERNEL_DTB=\"${dts_to_use}\"" >> project-spec/meta-user/conf/petalinuxbsp.conf"  in project root after go to build directory 
cd buuild  run the petalinuux-build command after successfull build, run the petalinux-config -c kernel command in <project-root>  enable the AD9371 drivers save it and exit, then run the petalinux-build command in proj-root . i got an error regarding Device-Tree how to reslove this issue.

**Screenshots**
![Error regarding Device-Tree](https://github.com/analogdevicesinc/meta-adi/assets/111216777/64f386d1-48bd-4734-b320-09f7c37b9500)

**Comment by nunojsa** [comment]
Hi,

The error is telling you everything. Look at the name of your devicetree... It does not look good and the system cannot find a matching pl-delete-nodes- file.

**Comment by pollai2** [comment]
Hi

Thanks for your reply. I had solved  this error and also  generate the
bootable images .

Regards
P.Prasanth
