### ISSUE TITLE
Device tree changes to use external clock FMCOMMS5

### ISSUE THREAD

**Issue by DiogoBaptistaBosch** [analogdevicesinc/meta-adi#152]
Hello,

I am using the following environment:
 - Project to build: ZCU102+FMCOMMS5
 - Petalinux version: 2022.2
 - HDL branch: 2022.22
 - META-ADI branch: 2022.2

I just made the hw changes to use the FMCOMMS5 with external clock. I want to make the device tree changes but I am not quite sure were can I make them. I am using a 40MHz external clock by the way.

Thanks in advance!

**Comment by nunojsa** [comment]
Hi,

I would say to change the [system-user.dtsi](https://github.com/analogdevicesinc/meta-adi/tree/main/meta-adi-xilinx#extending-the-devicetree) file...
