### ISSUE TITLE
 Could not find “pl-delete-nodes-.dtsi” when building PYNQ v3.0 image

### ISSUE THREAD

**Issue by Marvelous-coco** [analogdevicesinc/meta-adi#155]
**Environment (please complete the following information):**
 - Project to build:PYNQ image v3.0
 - Petalinux version:2022.1
 - HDL branch:2022_R2
 - META-ADI branch:2022_R2
 - Using meta-adi petalinux docker image?  
Board name : zedboard
Ubuntu 20.04
Vivado+Vitis 2022.1

BUILD STEPS:
1. Build HDL tp generate .xsa and bitstream
2. Create PetaLinux BSP
![3](https://github.com/user-attachments/assets/4cd60804-b97e-424c-bb81-ffc1360200b1)

then export BSP file.
3. Build PYNQ
* Clone PYNQ and checkout at branch image_v3.0
* Prepare board folder, this is the ZedBoard-ADI.spec:
ARCH_ZedBoard-ADI := arm
BSP_ZedBoard-ADI := ZedBoard-ADI.bsp
BITSTREAM_ZedBoard-ADI := system_top.bit
STAGE4_PACKAGES_ZedBoard-ADI := ethernet
* Prepare prebuilt image: 
![4](https://github.com/user-attachments/assets/0992a22d-6e2d-4770-8942-ea14cbf010bc)

* Run make
make BOARDS=ZedBoard-ADI
---------------------------------------------------------------------------------------------------------
ISSUE:
![5](https://github.com/user-attachments/assets/42d1c70e-0644-4447-a783-cc1153028a56)
I checked the file "pl-delete-nodes-.dtsi" in the folder, there exists many files pl-delete-nodes-*.dtsi, os i don't know why it canit find the file. Can anybuddy help me?

**Comment by nunojsa** [comment]
Hi,

Well, you're not defining the devicetree for your project as specified in the docs:

```
# Select the devicetree that fits the project being built
echo "KERNEL_DTB=\"${dts_to_use}\"" >> project-spec/meta-user/conf/petalinuxbsp.conf
```

Also note that I'm not sure what you're doing after step 3 but that's a workflow that was never really tested... If you have the .xsa file and passed it into `petalinux-config` that should be all you need.

**Comment by nunojsa** [comment]
Closing...
