### ISSUE TITLE
Using custom device treee

### ISSUE THREAD

**Issue by noelpedro** [analogdevicesinc/meta-adi#46]
Hello guys I'm using meta-adi to build zyqnqMP zcu102 fmcomms2 Ad 9361 ADI image. However I want to make a simple change to the device tree .i.e I want to change the rate of the external clock from 40MHz to 10MHz of AD9361. How can I ensure that petalinux uses this updated device tree?

**Comment by nunojsa** [comment]
Maybe take a look at [Extending the devicetree](https://github.com/analogdevicesinc/meta-adi/tree/master/meta-adi-xilinx#extending-the-devicetree)...

**Comment by noelpedro** [comment]
So I can copy the ad-fmcomms2.dtsi onto petalinux's system-user.dtsi then make the changes?

**Comment by nunojsa** [comment]
No, you can just overwrite the node you want in `system-user.dtsi`. No need to copy the full file...

**Comment by nunojsa** [comment]
Since it seems there's not more questions about this, I'm closing this issue...

**Comment by noelpedro** [comment]
Big thanks
