### ISSUE TITLE
Cant use rootFS from SD card

### ISSUE THREAD

**Issue by noelpedro** [analogdevicesinc/meta-adi#55]
Hi guys  I successfully buillt peta-linux 2018.3 project using meta-adi/oring/2018_R2 yocto layers for zynqMP-zcu102-ad9361-fmcomms2-3.

I have two issues. I initiailly tried to use IntraramFS for root filesystem. However i couldnt login as root even though I entered the correct password. Per $;petalinux-config -c rootfs -> image settings Password.

Because of this I configured the project to use SD card for rootFS i.e. /dev/mmcblk0p2.
That resulted in a kenel panic. 

"VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
Please append a correct "root=" boot option; here are the available partitions:..."

Anyone have success with ZCU102??

**Comment by nunojsa** [comment]
> Hi guys I successfully buillt peta-linux 2018.3 project using meta-adi/oring/2018_R2 yocto layers for zynqMP-zcu102-ad9361-fmcomms2-3.
 
You should not be using petalinux 2018.3 with our 2018_R2 branch. If you want to stick with tag petalinux version, you should use the 2019_R1 branch. Alternatively, you can use petalinux 2018.2 with the branch you are currently using.

After that, if you still have issues, I will have to try and reproduce them on my side.

> I have two issues. I initiailly tried to use IntraramFS for root filesystem. However i couldnt login as root even though I entered the correct password. Per $;petalinux-config -c rootfs -> image settings Password.

The password you should use is __analog__. That should work. We are probably overwriting the password to enforce our own pass.

Hope this helps!

**Comment by noelpedro** [comment]
I’m also having issues with rootfs o SD on zcu102 with petalinux 2018.3 using just the Xilinx kernel not the meta-adi yocto layer. 


So this issue must be with Xilinx and not with your layer.



💯

**Comment by nunojsa** [comment]
Hi,

Not sure this is actually an issue. Just double check your bootargs. Most likely, you are missing the `root=/dev/mmcblk0p2` argument.

**Comment by noelpedro** [comment]
Thanks for reply,

I re-imaged my SD card and..... BOOM it mounts the Rootfs on mmcblk0p2.
